# Sesión 05: Práctica con Python y Pandas

-----

In [1]:
import pandas as pd

In [32]:
ventas = pd.read_csv("./resource/05_ventas.csv")

In [33]:
ventas.head()

   id       ciudad  edad  genero     mes  ordenes  pago  usd
0   1  Guadalajara    33    Male  Jan 20        0     0    0
1   2  Guadalajara    23  Female  Jan 20        3     1  327
2   3    Monterrey    23  Female  Jan 20        1     0   28
3   4         Leon    24  Female  Jan 20        0     0    0
4   5       Puebla    46    Male  Jan 20        2     1  456

### **Caso práctico:**

Se tiene una base de datos de los clientes de una empresa con su comportamiento de compra en los meses de Enero a Abril del 2020 y 2021, con la siguiente información:

- id: Número único de registro del cliente.

- ciudad: Ciudad donde se encuentra la tienda.

- edad: Edad actual.

- genero: Género (Female / Male).

- mes: Mes en el que se realizó la orden.

- ordenes: Número de órdenes generadas en el mes.

- paid: Variable que indica si las órdenes fueron pagadas o no (1 Si, 0 No)

- usd: Dólares del total de órdenes generadas.

### Ejercicio 1

- Asigna a cada uno de los IDs su generación de edad en una nueva columna en base a lo siguiente.
    - Gen Z: 18 - 25
    - Millenials: 26 - 41
    - Gen X: 42 - 57
    - Boomers: 58 - 67

- Calcula por periodo:
    - Total de órdenes mensuales
    - Promedio mensual de USD (Total de USD por mes / Total de órdenes)
    - Total de USD

- Contesta las siguientes preguntas:
    - ¿Quién es el grupo de edad con más ventas totales después del 2021?
    - ¿Cuántas órdenes hay sin pagar del mes de Febrero de 2021?

### 0 

Comienza viendo tu dataset

In [34]:
ventas.head(5)

   id       ciudad  edad  genero     mes  ordenes  pago  usd
0   1  Guadalajara    33    Male  Jan 20        0     0    0
1   2  Guadalajara    23  Female  Jan 20        3     1  327
2   3    Monterrey    23  Female  Jan 20        1     0   28
3   4         Leon    24  Female  Jan 20        0     0    0
4   5       Puebla    46    Male  Jan 20        2     1  456

In [35]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       4000 non-null   int64
 1   ciudad   4000 non-null   object
 2   edad     4000 non-null   int64
 3   genero   4000 non-null   object
 4   mes      4000 non-null   object
 5   ordenes  4000 non-null   int64
 6   pago     4000 non-null   int64
 7   usd      4000 non-null   int64
dtypes: int64(5), object(3)
memory usage: 250.1+ KB

### 1.1 Asignar los grupos de edad. 

**HINT**: Usar función `pd.cut()`

In [36]:

bins = [0, 18, 25, 41, 57, 67, 100] 
labels = ["Menor de edad", "Gen Z", "Millennials", "Gen X", "Boomers", "Otra generación"]

ventas["Generacion"] = pd.cut(ventas["edad"], bins=bins, labels=labels, right=True)

ventas.head(5)

   id       ciudad  edad  genero     mes  ordenes  pago  usd   Generacion
0   1  Guadalajara    33    Male  Jan 20        0     0    0  Millennials
1   2  Guadalajara    23  Female  Jan 20        3     1  327        Gen Z
2   3    Monterrey    23  Female  Jan 20        1     0   28        Gen Z
3   4         Leon    24  Female  Jan 20        0     0    0        Gen Z
4   5       Puebla    46    Male  Jan 20        2     1  456        Gen X

In [44]:
ventas['ordenes'].unique()

array([0, 3, 1, 2, 4, 5, 7, 6, 8])

### 1.2 Calcular para los meses de 2021: 

**HINT**: Es necesario primero convertir la columna 'mes' a datetime. 

- Total de órdenes mensuales

- Promedio mensual de USD (Total de USD por mes / Total de órdenes)

- Total de USD

In [ ]:
ventas["mes"] = pd.to_datetime(ventas["mes"], format="%b %y")

ventas.head(5)

   id       ciudad  edad  genero        mes  ordenes  pago  usd   Generacion
0   1  Guadalajara    33    Male 2020-01-01        0     0    0  Millennials
1   2  Guadalajara    23  Female 2020-01-01        3     1  327        Gen Z
2   3    Monterrey    23  Female 2020-01-01        1     0   28        Gen Z
3   4         Leon    24  Female 2020-01-01        0     0    0        Gen Z
4   5       Puebla    46    Male 2020-01-01        2     1  456        Gen X

- Total de órdenes mensuales

In [59]:
filtro_mes = pd.to_datetime("2021-01-01")

ventas_mes = ventas[ventas["mes"] >= filtro_mes].groupby('mes')['ordenes'].sum()

ventas_mes

mes
2021-01-01    1484
2021-02-01    1242
2021-03-01    1556
2021-04-01    1310
Name: ordenes, dtype: int64

- Promedio mensual de USD por orden (Suma de USD / Total de órdenes)

In [60]:
ventas_ordenes_promedo = ventas[ventas["mes"] >= filtro_mes].groupby("mes").agg({"usd" : "sum", "ordenes" :"sum"})
ventas_ordenes_promedo["result"] = ventas_ordenes_promedo["usd"]/ventas_ordenes_promedo["ordenes"]
ventas_ordenes_promedo["result"]

mes
2021-01-01    195.320081
2021-02-01    157.739130
2021-03-01    204.662596
2021-04-01    150.182443
Name: result, dtype: float64

- Total de USD por mes

In [61]:
ventas_mes_usd = ventas[ventas['mes'] >= filtro_mes].groupby("mes")["usd"].sum()

ventas_mes_usd.head()

mes
2021-01-01    289855
2021-02-01    195912
2021-03-01    318455
2021-04-01    196739
Name: usd, dtype: int64

### 1.3 Cálculo después de 2021:

- ¿Quién es el grupo de edad con más ventas totales después del 2021?

- ¿Cuántas órdenes hay sin pagar del mes de Febrero de 2021?

In [62]:
fecha = pd.to_datetime("2021-01-01")

grupos_edad_filtro = ventas[ventas["mes"] >= fecha]

grupos_edad = grupos_edad_filtro.groupby("Generacion")["usd"].sum().idxmax()
grupos_edad

/tmp/ipykernel_8130/279341245.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grupos_edad = grupos_edad_filtro.groupby("Generacion")["usd"].sum().idxmax()

'Millennials'

- ¿Cuántas órdenes hay sin pagar del mes de Febrero de 2021?

In [41]:
fechas_filtro = pd.to_datetime("2021-02-01")

ventas_2021_02 = ventas[ventas['mes'] == fechas_filtro]

total_ordenes_sin_pago = ventas_2021_02[ventas_2021_02["pago"] == 0]['id'].count()

total_ordenes_sin_pago

np.int64(115)

- Agrega un impuesto del 16% a aquellas órdenes que sean compradas en Guadalajara

**HINT**: Usa  `apply` y `lambda` sobre las columnas de `usd` y `ciudad`.

Por ejemplo: 

`df[['columna_a','columna_b']].apply(lambda x: 1 if x['columna_a'] > x['columna_b'] else 0, axis = 1)`

`axis = 1` se usa cuando aplicas la función sobre más de una columna

In [51]:
ventas.head()

,id,ciudad,edad,genero,mes,ordenes,pago,usd,Generacion,usd + impuesto
0,1,Guadalajara,33,Male,2020-01-01,0,0,0,Millennials,0.00
1,2,Guadalajara,23,Female,2020-01-01,3,1,327,Gen Z,379.32
2,3,Monterrey,23,Female,2020-01-01,1,0,28,Gen Z,0.00
3,4,Leon,24,Female,2020-01-01,0,0,0,Gen Z,0.00
4,5,Puebla,46,Male,2020-01-01,2,1,456,Gen X,0.00

In [ ]:
def impuesto_guadalajara(price):
    return price * 1.16

fecha = pd.to_datetime("2021-01-01")

filtro_edad = ventas[ventas["mes"] >= fecha]

filtro_edad["usd_con_impuesto"] = filtro_edad[["ciudad", "usd"]].apply(
    lambda x: x["usd"] * 1.16 if x["ciudad"] == "Guadalajara" else x["usd"], axis=1
)

filtro_edad.head()

/tmp/ipykernel_8130/1355881067.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtro_edad["usd_con_impuesto"] = filtro_edad[["ciudad", "usd"]].apply(

,id,ciudad,edad,genero,mes,ordenes,pago,usd,Generacion,usd + impuesto,usd_con_impuesto
2000,1,Guadalajara,33,Male,2021-01-01,6,1,2577,Millennials,NaN,2989.32
2001,2,Guadalajara,23,Female,2021-01-01,4,1,1533,Gen Z,NaN,1778.28
2002,3,Monterrey,23,Female,2021-01-01,5,1,1132,Gen Z,NaN,1132.00
2003,4,Leon,24,Female,2021-01-01,7,1,2705,Gen Z,NaN,2705.00
2004,5,Puebla,46,Male,2021-01-01,3,1,1068,Gen X,NaN,1068.00